// ============================================================
// ĐĂNG TIÊN MỘNG — lore (flavor) 109 thẻ MỚI. Soạn qua workflow 6-agent (5 hệ + neutral/Thần Thoại)
// + harmonize (giọng võ lâm/tu tiên, tiếng Việt CÓ DẤU, không chép nguyên). 17 thẻ [C] cũ giữ flavor trong POOL.
// Số DRAFT về nội dung — user tinh chỉnh thẻ nào chưa ưng.
// ============================================================
export const CARD_LORE = {
  // --- KIM ---
  kimCangGiap: 'Vận Chân Khí thành lớp Kim Cang hộ thể. Đao thương chạm vào chỉ trượt khỏi thân, giúp giảm mạnh sát thương từ ngoại lực.',
  phanChanChuong: 'Mượn lực đối phương để phản chấn. Đòn đánh nhận vào càng mạnh, lực bật trả lại càng dữ, khiến kẻ tấn công tự chịu thương tổn.',
  tieuThietChuong: 'Tôi luyện song thủ như sắt nóng, khiến chưởng lực mang sức phá kim loại. Một chưởng toàn lực đủ làm gang thép biến dạng.',
  phaThietChuy: 'Dồn sức nặng như đất trời vào một chùy rồi giáng xuống điểm yếu. Trọng giáp dày cũng khó chịu nổi, uy lực nặng nề và phá giáp rất mạnh.',
  thietTuongBich: 'Đứng vững như một bức tường sắt, chặn mọi đòn đánh trước thân. Lối thủ bất động, thích hợp án ngữ và bảo vệ tuyến sau.',
  phaGiapTamChuy: 'Ba chùy nối tiếp như ba tiếng sấm: chùy đầu phá giáp, chùy hai làm suy yếu thân thể, chùy cuối dùng để kết liễu.',
  kimCuongPhachToai: 'Dồn Kim Cang Kình vào song thủ, tung một chưởng nặng như búa thần. Sức phá cực lớn, đặc biệt hữu hiệu trước mục tiêu cứng.',
  thietBoSam: 'Luyện da thịt bền như áo sắt, khiến đao kiếm chỉ để lại vết nhẹ. Ngoại công mạnh, bên trong lại có Thiền Công giữ thân ổn định.',
  viDaChuong: 'Chưởng pháp mang tên Vi Đà Tôn Giả, đường đường chính chính, cứng mà không thô. Vừa có sức hàng ma, vừa giữ được thế hộ thân.',
  baNhaThung: 'Kình lực rung như tiếng đại hồng chung, không cần đánh mạnh ngoài da mà chấn thẳng vào phủ tạng. Uy lực âm kình rất khó phòng bị.',
  vanVuThan: 'Thân pháp nhẹ như mây, thoắt ẩn thoắt hiện. Đối thủ khó xác định vị trí, thích hợp né tránh và đổi thế liên tục.',
  ngocLoTuKhi: 'Thu Linh Khí như hứng sương mai, dẫn về đan điền. Chân Nguyên sinh sôi đều đặn, giúp Nội Lực hồi phục bền bỉ.',
  phiKiemTruyThan: 'Ngự Khí điều khiển phi kiếm, cách xa vẫn có thể truy kích mục tiêu. Kiếm Quang nhanh như sao băng, chuyên đánh bất ngờ vào yếu điểm.',
  thanhVanBo: 'Đạp Thanh Vân mà bước, thân pháp nhẹ như lướt gió. Tiến lui linh hoạt, tốc độ cao và rất khó bị giữ chân.',
  tienNhanChiLo: 'Dồn Kiếm Khí vào đầu ngón rồi điểm thẳng huyệt đạo. Động tác nhìn nhẹ nhàng nhưng giấu sát cơ, trúng điểm yếu có thể lập tức xoay chuyển thế trận.',
  luuVanPhi: 'Kiếm thế trôi nhẹ như mây rồi bất chợt hóa thành cuồng phong. Hư thực đan xen, khiến đối thủ khó đoán hướng ra chiêu.',
  tieuDaoDonKiem: 'Người kiếm hợp nhất, ngự kiếm hóa quang lao đi cực nhanh. Thân ảnh đến đi gần như không dấu, thiên về cơ động và thoát chiến.',
  // --- MỘC ---
  manThienPhi: 'Ám khí Đường Môn tung ra như mưa thép che kín khoảng trời. Số lượng lớn khiến nhiều mục tiêu cùng lúc khó né tránh.',
  thoiTamChau: 'Thủ pháp Đường Môn âm nhu, bắn một viên Tụ Châu thẳng vào tâm mạch. Bề ngoài nhẹ nhàng nhưng kình lực ẩn sâu, khi nhận ra thì thương tổn đã ngấm vào trong.',
  phiTienThuat: 'Xạ thuật chân truyền Đường Môn, mũi tên rời cung nhanh như sao băng. Chuyên nhắm yếu điểm từ xa, ra tay nhanh đến mức đối thủ khó kịp phản ứng.',
  tuTinhCham: 'Độc châm tím biếc mảnh như tơ, lẩn vào gió gần như không tiếng động. Chỉ cần sượt qua da, Kịch Độc đã bắt đầu ngấm vào gân cốt.',
  khongMinhVu: 'Nỏ liên châu cải tiến từ di pháp Khổng Minh, mỗi lần kích hoạt bắn ra liên tiếp nhiều mũi tên. Nhịp bắn dày, tạo áp lực liên tục.',
  vanTienTruQuang: 'Xạ thuật đỉnh cao của Đường Môn: vạn tiễn bay lên rồi đồng loạt truy theo mục tiêu. Một khi đã khóa, rất khó thoát khỏi lưới tên.',
  ngungDocTan: 'Độc công nhập môn Ngũ Độc, luyện nhiều loại độc trùng thành bột tán. Khi phát tán theo gió, người hít phải sẽ nhanh chóng tê dại tay chân.',
  vanDocQuiTong: 'Đại pháp trấn giáo Ngũ Độc, gom nhiều loại Kịch Độc chồng lên nhau. Độc càng lưu lâu càng mạnh, liên tục bào mòn tạng phủ đối thủ.',
  docLongToa: 'Cầm nã tẩm độc, dùng xích độc quấn chặt mục tiêu như trăn siết mồi. Đối thủ càng vùng vẫy, độc càng thấm sâu theo khớp xương.',
  tanDocThu: 'Chưởng pháp âm độc Ngũ Độc, mười ngón tung ra một màn độc vụ lạnh. Trúng chưởng sẽ khiến Hàn Độc lan theo kinh mạch, làm khí huyết chậm và thân thể khó điều khiển.',
  nguDocXaTien: 'Ám khí độc môn Ngũ Độc, mũi tên khắc đầu rắn và tẩm nọc của năm loại độc trùng. Khi trúng, độc nhanh chóng theo máu lan về tâm mạch.',
  cotDocChuong: 'Chưởng công Ngũ Độc đưa kình lực xuyên qua da thịt rồi ngấm vào xương. Bên ngoài ít để lại dấu, nhưng Cốt Độc khiến gân cốt dần tê liệt.',
  bachDocPhat: 'Tuyệt kỹ Ngũ Độc kích phát cùng lúc hàng trăm loại độc đã tích trong cơ thể. Bách Độc bùng lên trong chớp mắt, gây thương tổn cực mạnh từ bên trong.',
  huyetMaCong: 'Tà công trấn phái Ma Giáo, kích huyết khí sôi trào để đổi lấy sức mạnh bạo liệt. Càng đánh càng cuồng, nhưng dùng lâu sẽ hao tổn Chân Nguyên.',
  nhiepHonThuat: 'Nhiếp tâm tà thuật Ma Giáo, dùng ánh mắt và Ma Âm quấy nhiễu thần trí. Đối thủ có thể mất phương hướng hoặc bị khống chế trong chốc lát.',
  huyetTraoThu: 'Trảo pháp Ma Giáo, năm ngón cong như móc câu vừa xé thương vừa hút Huyết Khí. Càng đánh trúng nhiều, khí thế càng cuồng bạo.',
  thichHuyetChu: 'Huyết Chú Ma Giáo khắc lời nguyền lên mục tiêu rồi hút dần Tinh Huyết theo thời gian. Hiệu ứng kéo dài, âm hiểm và khó gỡ.',
  huyetTeChuong: 'Chưởng pháp Ma Giáo lấy máu làm dẫn để kích Ma Khí. Một chưởng bộc phát sát lực rất lớn, nhưng người thi triển cũng phải tiêu hao Huyết Khí của chính mình.',
  phanHuyetHoiNguyen: 'Bí pháp hồi nguyên Ma Giáo, đốt Huyết Khí để ép Chân Nguyên phục hồi nhanh. Hiệu quả tức thời rất mạnh nhưng phải trả giá bằng sức khỏe lâu dài.',
  // --- THỦY ---
  phatQuangKinh: 'Tâm Kinh trấn phái dẫn Phật Quang bao quanh cơ thể. Có tác dụng bảo hộ, áp chế Tà Khí và tăng khả năng chống đỡ.',
  phoDoTe: 'Phật pháp từ bi tụng kinh cứu độ. Cam Lồ hồi phục thương tổn, có thể cứu đồng đạo đang ở sát bờ sinh tử.',
  thanhTamChu: 'Chú Tịnh Tâm giúp thần trí lắng lại, xua tan tà niệm và hiệu ứng mê hoặc. Linh Đài trở nên trong sáng, khó bị nhiễu tâm.',
  phoHienChuong: 'Chưởng pháp mang danh Phổ Hiền, cương nhu hài hòa. Vừa bảo hộ bản thân, vừa dùng chưởng lực trầm ổn để chế ngự đối thủ.',
  chuDuongTamChu: 'Bí chú dưỡng tâm hộ mệnh, củng cố Nguyên Thần và Tâm Mạch. Tăng khả năng chống Tà Độc, đồng thời giúp Khí Huyết ổn định.',
  tuBiPhoDo: 'Lấy lòng từ bi làm gốc, chưởng lực vừa hàng ma vừa hộ đạo. Uy lực không thiên về sát phạt đơn thuần mà còn mang hiệu quả trợ lực và bảo hộ.',
  matKiem: 'Kiếm pháp Hoa Sơn ẩn hiện như hoa mai nở giữa tuyết. Sát cơ giấu trong thế kiếm thanh nhã, thường đánh trúng trước khi đối thủ kịp nhận ra.',
  phaKiemThuc: 'Tuyệt học chuyên phá chiêu, nhắm thẳng vào sơ hở trong kiếm thế của đối phương. Chỉ cần bắt đúng một điểm, cả chuỗi kiếm pháp có thể bị phá tan.',
  cuongPhongKiem: 'Kiếm ý như cuồng phong, biến hóa khó đoán. Hư thực đổi liên tục, khiến đối thủ rất khó theo kịp nhịp kiếm.',
  lacThacKiem: 'Kiếm thế phóng khoáng như người say, nhìn lỏng lẻo nhưng trong mỗi sơ hở đều giấu đòn hiểm. Càng khó đoán, càng dễ bất ngờ đoạt thế.',
  ngocNuKiem: 'Kiếm pháp thanh tú, mềm mại và tinh xảo. Song kiếm phối hợp như hình với bóng, đẹp mắt nhưng không thiếu sát lực.',
  tuTuKiem: 'Kiếm Quang tản ra như liễu nhứ đầy trời, bao phủ bốn phía. Đối thủ dễ lạc giữa tầng tầng kiếm ảnh và khó tìm đường thoát.',
  hanBangChuong: 'Chưởng trấn phái Thúy Yên, Hàn Khí thấm sâu vào xương. Trúng đòn sẽ khiến gân cốt tê cứng và khí huyết lưu chuyển chậm lại.',
  bangPhongToa: 'Vận Huyền Công đóng băng không gian quanh mục tiêu như một lao ngục vô hình. Chưởng vừa phát, bước chân đối thủ bị khóa, tiến lui đều khó.',
  vanLyBangPhong: 'Kiếm Quang cuốn Hàn Sương như bão tuyết kéo dài vạn dặm. Một kiếm quét ra vừa gây thương tổn vừa áp chế thế công của đối thủ.',
  bangChamThich: 'Ngưng Hàn Khí thành Băng Châm, ra tay nhanh và gần như không tiếng. Điểm trúng huyệt đạo sẽ khiến đối thủ tê buốt và khó vận lực.',
  lanhSuongThu: 'Thủ pháp hộ thân Thúy Yên tạo màn Lãnh Sương quanh cơ thể. Vừa che thân, vừa khiến kẻ áp sát chịu Hàn Khí và chậm tay.',
  bangPhongChuong: 'Dồn Băng Phong vào một chưởng rồi bộc phát như bão tuyết. Hàn Khí phong bế kinh mạch, khiến tay chân đối thủ tê liệt.',
  tuyetPhongChuong: 'Tuyệt học Thúy Yên cuốn Tuyết Phong thành luồng Hàn Khí dữ dội. Một chưởng quét qua như tuyết bạo, phủ kín đối thủ trong giá lạnh.',
  // --- HỎA ---
  phanThienChuong: 'Tâm Hỏa dồn vào một chưởng Phần Thiên. Nhiệt lực bùng lên dữ dội, thiên về sát thương Hỏa cực mạnh và thiêu đốt trực tiếp.',
  hoaVanCuongPhong: 'Chưởng phong cuốn Hỏa Độc thành luồng gió nóng quét ngang chiến trường. Đối thủ trong vùng ảnh hưởng liên tục chịu thiêu đốt và khó rút lui.',
  liaoNguyenChiHoa: 'Nguyên Hỏa từ đan điền phun trào rồi lan rộng như lửa cháy đồng. Ngọn lửa bám dai, càng kéo dài càng khó dập.',
  tinhHoaMoi: 'Một tia lửa nhỏ làm mồi, âm thầm bén dần rồi bất chợt bùng lớn. Đối thủ thường chưa kịp nhận ra thì Hỏa Thế đã lan rộng.',
  lieuHoaChuong: 'Mỗi chưởng gieo một mồi Hỏa Độc lên mục tiêu. Đối thủ càng cử động, ngọn lửa càng lan, gây thương tổn âm ỉ kéo dài.',
  phanThienDoiHoa: 'Dùng Hỏa Kình đối đầu trực diện với Hỏa lực đối phương. Một chưởng bùng nổ mạnh, áp chế phản kích và thiêu sạch vùng giao chiến.',
  phucDiaHoaVan: 'Hỏa Vân phủ kín mặt đất thành một vùng cháy. Dù đứng yên hay di chuyển, đối thủ trong khu vực đều liên tục chịu Hỏa thương.',
  tuyQuyen: 'Say mà không loạn, thân hình nghiêng ngả nhưng chiêu thức rất hiểm. Nhìn tưởng mất thăng bằng, thật ra mỗi cú vung tay đều giấu sát cơ.',
  khangLongTamChuong: 'Chưởng lực chính đại, tiếng ngân như rồng. Một chưởng đẩy ra mạnh mẽ, đủ khiến đối thủ nặng cũng phải lùi bước.',
  khangLongThapBatChuong: 'Mười tám chưởng lấy Dịch Lý làm nền, cương mạnh nhưng không cứng nhắc. Mỗi chưởng như Thần Long xuất hải, uy lực lớn và khí thế đường hoàng.',
  khaiTuuThuc: 'Mượn men rượu khai mạch, khiến Khí Lực bùng lên. Uống càng đúng lúc, thế đánh càng hăng và quyền cước càng dồn dập.',
  dangLongCuoc: 'Mượn thế rồng bay để tung một cước từ trên cao. Sức cước nặng như sấm bổ, uy lực lớn và khó né.',
  tiemThienChuong: 'Lấy nhu chứa cương, giấu Chưởng Kình chưa phát như rồng ẩn vực sâu. Khi thời cơ tới, đòn bộc phát bất ngờ và rất khó cản.',
  phiLongTaiThien: 'Chưởng thế như rồng bay giữa trời, khí thế bao trùm bốn phía. Một chưởng quét ngang mạnh mẽ, thiên về áp đảo trực diện.',
  nhatNguyetTamPhap: 'Dung hợp Nhật Nguyệt và Âm Dương thành một mạch. Nội tức dày và tăng dần theo tu luyện, là nền tảng cho nhiều tà công của Thần Giáo.',
  quangMinhTanPhap: 'Chân Khí tỏa sáng như mặt trời, bùng ra bốn phía. Ánh quang vừa gây áp lực vừa làm rối mắt quần địch.',
  huyetTeThuc: 'Lấy máu làm dẫn để gọi Sát Khí nhập thân. Uy lực tăng mạnh nhưng mỗi lần thi triển đều phải trả giá bằng Huyết Khí.',
  phanHuyetChuong: 'Đốt Khí Huyết thành Chưởng Phong đỏ sẫm. Khi trúng đòn, Huyết Khí trong cơ thể mục tiêu bị kích loạn, gây đau đớn và thương tổn lớn.',
  nhiepHuyetThuc: 'Hút Tinh Huyết của đối thủ để bồi bổ bản thân. Địch càng suy, người thi triển càng mạnh, nhưng dùng lâu dễ tích tụ Tà Khí và sinh hậu họa.',
  huyetHaiThichCot: 'Một chiêu hiểm độc như biển máu tràn tới, Sát Khí lạnh thấu xương. Gây thương tổn sâu và có khả năng kết liễu mục tiêu đang suy yếu.',
  // --- THỔ ---
  lienHoanThoiTuy: 'Chưởng pháp Võ Đang liên miên không dứt, một thức nối một thức như sóng tầng. Ép đối thủ liên tục, khó tìm khoảng trống để phản công.',
  tuLuongBatThienCan: 'Diệu lý Thái Cực, mượn lực hoàn lực. Dùng nhu chế cương, đối thủ càng đánh mạnh càng dễ bị chính lực của mình phản lại.',
  luongNghiThuc: 'Kiếm ý Võ Đang phân thành Âm Dương Lưỡng Nghi. Hư thực đan xen như hai người cùng vây đánh, khiến đối thủ khó phân biệt thật giả.',
  nhuVanChuong: 'Chưởng phong mềm như mây, gần như vô hình. Kình lực âm thầm thấm vào trong, khi đối thủ nhận ra thì thương tổn đã lan đến tạng phủ.',
  thaiCucNhuKinh: 'Tinh túy Thái Cực: lấy nhu khắc cương, lấy tĩnh chế động. Kình lực vận theo vòng tròn liên tục, dẫn và hóa giải sức đánh của đối thủ.',
  luongNghiSinhTu: 'Thượng thừa Võ Đang, từ Lưỡng Nghi diễn hóa Tứ Tượng. Âm Dương xoay chuyển, một chưởng chứa nhiều biến hóa và khó đoán.',
  conLonChuong: 'Chưởng trấn phái Côn Lôn, khí thế rộng và hùng. Một chưởng mở ra như non núi trùng điệp, cương mãnh nhưng vẫn giữ thế chính đại.',
  toaThienCuong: 'Trận pháp Côn Lôn dẫn Khí Trời Đất thành lưới Thiên Cương. Khi bố trận hoàn chỉnh, đối thủ bị khóa bốn phía và khó thoát.',
  honNguyenNhatKhi: 'Nội công Côn Lôn gom Tinh, Khí, Thần về một mối. Chân Khí thuần hậu, càng luyện càng sâu, là nền cho nhiều Tuyệt Kỹ.',
  khaiThienXucDia: 'Tuyệt học Côn Lôn mang khí thế khai thiên lập địa. Một chiêu giáng xuống tạo Cương Kình bạo liệt, chuyên phá phòng thủ trực diện.',
  canKhonNhatChi: 'Chỉ pháp Côn Lôn dồn toàn bộ Chân Khí vào đầu ngón. Một chỉ cách không điểm huyệt, kình lực xuyên xa và đánh thẳng yếu điểm.',
  daoChuyenAmDuong: 'Bí thuật Côn Lôn đảo chuyển Khí Cơ, biến hư thành thực và đổi công thành thủ. Có thể làm rối vận hành Ngũ Hành của đối thủ, khiến lực phản ngược vào kinh mạch.',
  conLonTamThucKiem: 'Kiếm pháp Côn Lôn gồm ba thức liên hoàn, mỗi thức nối nhau như núi liền núi. Chiêu số không cầu kỳ nhưng uy lực lớn, thiên về kết liễu nhanh.',
  thienSonHanBang: 'Chưởng trấn Thiên Sơn mang Hàn Khí thấu xương. Khi chạm trúng, Khí Huyết đối thủ chậm lại, cơ thể dần tê cứng.',
  bangPhachHoThan: 'Hộ thân Thiên Sơn dùng Hàn Khí kết thành Băng Phách quanh người. Vừa tăng phòng thủ, vừa phản chấn một phần ngoại lực khi bị đánh.',
  lucDuongThanCong: 'Thần công Thuần Dương Thiên Sơn dung hợp sáu luồng Dương Khí. Có tác dụng điều hòa Hàn Nhiệt, hồi phục thương thế và tăng Công Lực.',
  thienSonChiHan: 'Chỉ pháp âm hàn Thiên Sơn ngưng Hàn Khí thành mũi Kim Băng. Điểm trúng huyệt sẽ phong bế kinh mạch, khiến đối thủ tê dại và khó vận công.',
  hoiXuanThuat: 'Y thuật Thiên Sơn dùng Chân Khí ôn hòa dẫn qua kinh mạch. Có thể hồi phục thương thế nặng và kéo người kiệt sức trở lại trạng thái chiến đấu.',
  hanBangChanKhi: 'Nội công Thiên Sơn tạo Chân Khí âm hàn tinh thuần lưu chuyển toàn thân. Đây là nền tảng cho các Băng Chưởng và Hàn Chỉ của bản phái.',
  thienSonBangPhong: 'Tuyệt học Thiên Sơn dồn Hàn Khí thành cuồng phong băng tuyết quét khắp chiến trường. Sương giá phủ rộng, vừa gây thương tổn vừa phong tỏa mục tiêu.',
  // --- Neutral (vô phái) ---
  coBanChuong: 'Một chưởng cơ bản, không hoa mỹ nhưng đường hoàng và ổn định. Là nền tảng đơn giản để luyện căn cơ trước khi học chiêu cao hơn.',
  hoThanBo: 'Dời bước né đòn, thu vai giữ thế. Bộ pháp chưa nổi danh nhưng đủ giúp tránh nhiều đòn và giữ mạng trong vòng vây.',
  vinhXuanChuy: 'Giữ trung tuyến, tung quyền thẳng liên hoàn. Ba quyền dồn vào một điểm, lấy tốc độ và khoảng cách ngắn để phân thắng bại.',
  vanKhiQuyet: 'Điều tức dẫn Khí, cho Chu Thiên vận hành đều đặn. Tạp niệm lắng xuống, đan điền ngày càng vững và Nội Tức sâu hơn.',
  toanPhongCuoc: 'Xoay người tung một cước quét ngang như cuồng phong. Thích hợp phá vòng vây và đánh nhiều mục tiêu xung quanh.',
  // --- THẦN THOẠI (bí kíp 9 huyền thoại) ---
  camHuongHoaiCotTan: 'Hương thơm ngọt ngào che giấu Hoại Cốt Độc. Kẻ trúng độc vẫn thấy dễ chịu trong lúc gân cốt dần suy yếu, rất khó phát hiện sớm.',
  tamCotDuongSinhCo: 'Cổ Tằm gặm xương và hút Nội Tức của đối thủ để dưỡng thân người thi triển. Mục tiêu càng vùng vẫy, độc càng lan sâu.',
  phanTamCuuDiem: 'Chín ngọn Liệt Diễm bùng lên như Hồng Liên, thiêu đốt mục tiêu từ ngoài vào trong. Là một chiêu Hỏa công có sức sát thương cực lớn.',
  phucMaBatDongThien: 'Tâm bất động như núi, thân vững như Kim Cang. Tà lực đánh tới bị hóa giải trước lớp hộ thể, tăng mạnh khả năng chống Tà Khí và giữ Đạo Tâm.',
  lacMaiNhatKiem: 'Một kiếm điểm ra nhẹ như hoa mai rơi, thanh nhã nhưng chí mạng. Kiếm thế ngắn gọn, nhắm thẳng yếu điểm để kết liễu.',
  hanhVanLuuThuyQuyet: 'Thân pháp và thế đánh liền mạch như mây trôi nước chảy. Đòn nối đòn không dứt, mềm mại nhưng đủ sức cuốn đối thủ theo nhịp.',
  doanHuyenThapTamTuyen: 'Mười ba dây đàn hóa thành mười ba đường sát cơ. Âm Ba đánh thẳng vào phủ tạng, gây thương tổn sâu dù bên ngoài gần như không thấy vết.',
  nhatNhanDoanMenhThich: 'Một ánh nhìn khóa điểm chí mệnh, một nhát thích lập tức ra tay. Tốc độ cực nhanh, chuyên kết liễu bằng một đòn chính xác.',
  hanBangCuuTuyetChuong: 'Chín thức Cực Hàn liên tiếp khóa Khí Huyết. Chưởng Phong đi đến đâu Sương Giá phủ đến đó, khiến kinh mạch tê cứng và dễ bị kết liễu.',
};
