// ============================================================
// ĐĂNG TIÊN MỘNG — lore (flavor) 109 thẻ MỚI. Soạn qua workflow 6-agent (5 hệ + neutral/Thần Thoại)
// + harmonize (giọng võ lâm/tu tiên, tiếng Việt CÓ DẤU, không chép nguyên). 17 thẻ [C] cũ giữ flavor trong POOL.
// Số DRAFT về nội dung — user tinh chỉnh thẻ nào chưa ưng.
// ============================================================
export const CARD_LORE = {
  // --- KIM ---
  kimCangGiap: 'Vận khí thành giáp, kim cương hộ thể. Đao thương chạm vào chỉ nghe chát một tiếng rồi trượt, thân như đúc thép; ngoại lực muôn trùng, khó tổn phân hào.',
  phanChanChuong: 'Mượn lực đánh lực, cương kình phản chấn. Địch vừa chạm đã bị bật ngược; đòn tới càng nặng, phản đòn càng dữ, tự chuốc thương vong.',
  tieuThietChuong: 'Song thủ tôi trong lửa sắt, thịt phàm hóa kim. Chưởng phong tới đâu thép nóng tan chảy tới đó; một chưởng giáng ra, gang sắt cũng tiêu.',
  phaThietChuy: 'Tụ sức nặng đất trời vào một chùy, nhằm hiểm mà giáng. Thiết giáp dày mấy tấc cũng vỡ nát; uy thế trầm hùng, long trời lở đất.',
  thietTuongBich: 'Đứng lặng như tường sắt sừng sững, muôn đòn dập tới đều chặn ngoài thân. Vững vàng bất động, một người án ngữ, vạn quân khó qua.',
  phaGiapTamChuy: 'Ba chùy liền nhau như sấm nối sấm. Chùy đầu phá giáp, chùy sau vỡ cốt, chùy cuối định mạng; giáp trụ dày mấy cũng khó đỡ trọn ba đòn.',
  kimCuongPhachToai: 'Vận Kim Cang bất hoại vào song thủ, một chưởng như búa thần bổ xuống. Đá tảng vỡ tan; tà ma nghe tiếng đã kinh hồn bạt vía.',
  thietBoSam: 'Luyện da thịt bền như áo sắt, đao kiếm chém vào chỉ để vệt trắng. Thân trần đỡ binh nhận; thiền công thâm hậu, ẩn tàng bên trong.',
  viDaChuong: 'Chưởng lấy tên Vi Đà tôn giả, đường hoàng chính đại, cương trung hàm nhu. Một chưởng phát ra hàng yêu phục ma, hộ trì Phật pháp.',
  baNhaThung: 'Kình lực rung ngân như đại hồng chung, đòn vô thanh mà chấn thẳng phủ tạng. Ngoài da lành lặn, nội phủ đã tan; âm ba khó lường.',
  vanVuThan: 'Bước đi như mây trôi mưa cuốn giữa non tiên, thoắt ẩn thoắt hiện phiêu hốt vô định. Địch hoa mắt chẳng lần được tung tích, nhẹ tựa vân yên.',
  ngocLoTuKhi: 'Hớp móc ngọc sương mai, tụ linh khí về đan điền. Chân nguyên ôn nhuận sinh sôi không dứt, tựa uống cam lộ tiên gia; nội tức miên miên bất tuyệt.',
  phiKiemTruyThan: 'Ngự khí điều kiếm, vượt trăm bước lấy đầu người. Kiếm quang lóe như sao băng truy hồn, nhanh đến thần cũng khó tránh; hình bóng chưa tan, mạng đã mất.',
  thanhVanBo: 'Chân đạp thanh vân, bước lên chín tầng trời. Thân khinh linh phiêu dật, tiến thoái tựa đạp mây lướt gió; phàm nhân trông theo, ngỡ tiên nhân giáng thế.',
  tienNhanChiLo: 'Một ngón trỏ ra như tiên nhân điểm hóa mê đồ. Kiếm khí tụ đầu ngón phóng thẳng huyệt đạo, tưởng nhàn nhã mà ẩn sát cơ; điểm trúng liền định thắng thua.',
  luuVanPhi: 'Kiếm đi như mây lành lững lờ, chợt bùng thành bão. Chiêu thức nhu hòa quấn quýt liên miên, trong nhẹ nhàng giấu sát ý, khiến địch khó dò hư thực.',
  tieuDaoDonKiem: 'Ngự kiếm độn quang, chớp mắt đã ngoài trăm dặm. Người kiếm hợp nhất tiêu diêu thiên địa, đến đi không dấu vết; phiêu nhiên thoát tục như bậc tiên gia du ngoạn.',
  // --- MỘC ---
  manThienPhi: 'Đường Môn ám khí, mười ngón nhất phất, trăm mũi phi hoàng che kín trời cao. Địch đông mấy vẫn khó bề né tránh, ngẩng đầu chỉ thấy mưa thép rợp che vạn dặm.',
  thoiTamChau: 'Đường Môn thủ pháp âm nhu, một viên tụ châu bắn thẳng tâm mạch. Ngoài xem nhàn tản mà bên trong hiểm hóc; trúng rồi mới hay kình lực đã xuyên tận đáy lòng.',
  phiTienThuat: 'Đường Môn xạ nghệ chân truyền, tiễn rời cung như sao băng xé gió. Trăm bước xuyên dương, mắt vừa chớp thì mũi tên đã cắm ngập nơi yếu hại.',
  tuTinhCham: 'Đường Môn độc châm bí truyền, thân kim tím biếc mảnh tựa tơ liễu. Vô thanh lẩn vào gió, sượt qua da thịt là kịch độc đã ngấm vào gân cốt.',
  khongMinhVu: 'Nỏ liên châu theo di pháp Khổng Minh, một cơ quan bật ra hàng loạt tiễn dày. Đường Môn cải tiến thêm phần tinh xảo, tay chưa ngừng thì tiễn chẳng dứt.',
  vanTienTruQuang: 'Đường Môn xạ thuật đỉnh cao, vạn tiễn đồng loạt vọt lên rồi lao xuống truy hình đuổi bóng. Đã khóa mục tiêu, dẫu chạy nhanh tựa ánh sáng cũng không thoát lưới tiễn.',
  ngungDocTan: 'Ngũ Độc nhập môn độc công, luyện trăm loài độc trùng thành một nắm bột tán. Gió thoảng qua kịch độc liền ngưng tụ lan khắp, kẻ hít phải tê dại tứ chi.',
  vanDocQuiTong: 'Ngũ Độc trấn giáo đại pháp, gom vạn độc thiên hạ quy về một mối. Độc chồng lên độc, càng lâu càng thịnh, khiến địch nhân ngũ tạng dần rữa nát.',
  docLongToa: 'Ngũ Độc cầm nã tẩm độc, xích long độc quấn siết như trăn siết mồi. Đã khóa được thì độc theo khớp xương chảy vào, càng vùng vẫy độc càng thấm sâu.',
  tanDocThu: 'Ngũ Độc chưởng pháp âm độc, mười ngón nhuộm chàm phất ra làn độc vụ. Vỗ trúng thân người là hàn độc tán khắp kinh mạch, khí huyết đình trệ chẳng còn nghe lời.',
  nguDocXaTien: 'Ngũ Độc ám khí độc môn, mũi tiễn khắc hình xà đầu tẩm nọc năm giống độc trùng. Tên bay rít lên như rắn phun nọc, trúng rồi độc theo máu bò thẳng về tim.',
  cotDocChuong: 'Ngũ Độc chưởng công thâm hiểm, kình lực xuyên da thịt thấm thẳng vào xương tủy. Trúng chưởng chẳng thấy vết ngoài, chỉ nghe cốt độc ăn dần đến khi gân cốt tê liệt.',
  bachDocPhat: 'Ngũ Độc tuyệt kỹ áp giáo, dồn trăm loại độc ẩn trong người rồi cùng lúc phát tác. Bách độc đồng thời bùng lên, kẻ trúng chỉ trong khoảnh khắc đã bị độc khí thiêu đốt lục phủ.',
  huyetMaCong: 'Ma Giáo trấn phái tà công, dẫn huyết khí sôi trào hóa thành cuồng lực bạo liệt. Càng đánh càng hăng như say máu, uy mãnh kinh người mà dễ tổn hại chân nguyên.',
  nhiepHonThuat: 'Ma Giáo nhiếp tâm tà thuật, ánh mắt cùng ma âm nhiễu loạn thần trí đối thủ. Hồn phách bị khống chế trong chớp mắt, kẻ địch ngơ ngác như mất cả tâm thần.',
  huyetTraoThu: 'Ma Giáo trảo pháp đẫm máu, năm ngón cong như móc câu xé toạc da thịt hút lấy huyết khí. Vuốt tới đâu máu bắn tới đó, càng cào càng thêm cuồng bạo.',
  thichHuyetChu: 'Ma Giáo huyết chú hút máu, khắc lời nguyền lên đối thủ để hằng đêm hút dần tinh huyết. Dính chú thì máu thịt hao mòn không dứt, uy lực âm hiểm khôn lường.',
  huyetTeChuong: 'Ma Giáo chưởng pháp tế luyện, lấy máu tươi làm lễ khơi ma khí trong lòng bàn tay. Một chưởng giáng xuống mang theo sát khí ngút trời, đổi mạng địch bằng chính huyết khí của mình.',
  phanHuyetHoiNguyen: 'Ma Giáo ma pháp hồi nguyên, đốt cháy huyết khí bức bách chân nguyên phục hồi. Trong chớp mắt bùng lên sinh cơ mãnh liệt, song đốt máu tiếp lực rốt cuộc là tổn thọ chuốc họa về sau.',
  // --- THỦY ---
  phatQuangKinh: 'Trấn phái tâm kinh, một niệm dẫn Phật quang phổ chiếu. Hào quang bao thân, tà khí bất xâm; gươm đao chạm tới, tan như sương tan dưới nắng.',
  phoDoTe: 'Đại lễ từ bi, tụng kinh cầu độ khổ nạn. Cam lồ tưới xuống, thương tổn tự lành; kéo đồng đạo bên bờ sinh tử về lại nhân gian.',
  thanhTamChu: 'Chú ngữ tịnh tâm truyền đời, một niệm tĩnh thì muôn niệm lặng. Tà mị nhiễu thần đều tan, linh đài trong vắt như hồ không gợn.',
  phoHienChuong: 'Chưởng mang hồng danh Bồ Tát, cương nhu tương tế mà từ bi. Ra chưởng trầm ổn như núi, vừa hộ thân che chở, vừa điểm hóa kẻ mê quay đầu.',
  chuDuongTamChu: 'Bí chú dưỡng tâm hộ mệnh, ngày đêm tụng niệm nuôi nguyên thần. Hộ tâm mạch vững, tà độc khó lấn; khí huyết tự an như suối chảy không ngừng.',
  tuBiPhoDo: 'Lòng từ bi làm gốc, một chưởng độ hết bể khổ chúng sinh. Vừa hàng ma vệ đạo, vừa gieo phúc lành như mưa pháp thấm nhuần vạn vật.',
  matKiem: 'Kiếm trấn sơn Hoa Sơn, chiêu ẩn hiện tựa mai nở giữa tuyết. Sát cơ giấu trong nét thanh nhã; địch chưa kịp thấy, đòn hiểm đã tới thân.',
  phaKiemThuc: 'Tuyệt học phá địch, chuyên nhắm sơ hở trong kiếm chiêu. Một điểm phá thế, trăm chiêu hoa mỹ của địch tan vỡ trong nháy mắt.',
  cuongPhongKiem: 'Kiếm ý cuồng phong vô định, thế biến ảo khôn lường. Ra chiêu như gió lốc cuốn qua, hư thực khó phân, địch chống đỡ không kịp trở tay.',
  lacThacKiem: 'Kiếm phóng túng buông thả, thế đi lãng đãng tựa kẻ say. Nhìn tưởng hờ hững vô lực, ngờ đâu trong sơ hở giấu sát cơ đoạt mệnh.',
  ngocNuKiem: 'Kiếm thanh tú như dáng ngọc nữ, thế mềm mại mà tinh diệu. Đôi kiếm hô ứng như bóng với hình, đẹp mà lợi hại khôn cùng.',
  tuTuKiem: 'Tuyệt kỹ tựa liễu nhứ đầy trời, kiếm quang giăng kín tứ phương. Điểm điểm hàn mang như bông liễu bay, địch lạc giữa trùng trùng kiếm ảnh.',
  hanBangChuong: 'Chưởng trấn phái Thúy Yên, hàn khí miên miên thấm tận cốt. Chưởng phong lạnh như băng tuyết cuốn qua; trúng đòn thì gân cốt tê cứng, khí huyết ngưng trệ.',
  bangPhongToa: 'Huyền công vận băng phong tỏa tứ phương, giá lạnh giăng thành lao ngục vô hình. Chưởng vừa ra, bước chân địch đông cứng, tiến thoái đều nan.',
  vanLyBangPhong: 'Kiếm mang khí thế vạn dặm băng phong, kiếm quang cuốn theo hàn sương. Một kiếm quét ra như bão tuyết ngàn trùng, đóng băng cả sát khí đối phương.',
  bangChamThich: 'Tụ hàn khí thành băng châm nhỏ nhọn, ra tay mau lẹ vô thanh. Mũi kiếm lạnh như kim băng đâm tới, điểm trúng huyệt đạo khiến địch tê buốt khôn lường.',
  lanhSuongThu: 'Thủ pháp hộ thân Thúy Yên, vận lãnh sương kết màn hàn khí quanh mình. Sương giăng che chắn thân pháp, vừa thủ vững, vừa khiến kẻ đến gần run tay chùn bước.',
  bangPhongChuong: 'Dồn băng phong vào một kích, hàn khí bộc phát như bão tuyết. Chưởng ra lạnh thấu tâm can, phong bế kinh mạch, tê liệt cả chân tay đối thủ.',
  tuyetPhongChuong: 'Tuyệt học Thúy Yên cuốn tuyết phong thành cuồng lưu giá lạnh, uy thế mãnh liệt khôn lường. Chưởng phong quét qua như trận tuyết bạo, vùi lấp địch trong hàn khí ngập trời.',
  // --- HỎA ---
  phanThienChuong: 'Tâm hỏa hun đúc, nhất chưởng phần thiên. Khí nóng bừng bừng, đá tan vàng chảy; chưởng chưa tới thân, địch đã hóa tro giữa cuồng viêm.',
  hoaVanCuongPhong: 'Chưởng phong cuốn mây, hỏa độc quét ngang. Cuồng phong hực nóng ập tới, thiêu tận vạn vật; địch tán trong biển lửa, tìm đường lui chẳng có.',
  liaoNguyenChiHoa: 'Nguyên hỏa từ đan điền phun trào, tinh hỏa liệu trọn cánh đồng. Ngọn lửa bất tận, càng cháy càng cuồng; đốt tận cội rễ, chẳng chừa mảy may.',
  tinhHoaMoi: 'Nhất tia làm mồi, ngọn lửa liên miên. Đốm hỏa âm ỉ bén dần, chớp mắt cháy lan; địch chưa hay biết, thế viêm đã khôn dập.',
  lieuHoaChuong: 'Mỗi chưởng gieo mồi, hỏa bén âm thầm. Địch càng cử động, viêm độc càng lan; thịt xương hun dần, đau âm ỉ chẳng tan trong khói lửa dai dẳng.',
  phanThienDoiHoa: 'Lấy lửa chọi lửa, dồn khí đối thiên. Nhất chưởng phần thiên bùng cháy ngất trời, đè bẹp phản kích; chiến địa thiêu sạch, chẳng còn lối phản công.',
  phucDiaHoaVan: 'Mây lửa phủ đất, chiến địa hóa thảm viêm. Bước chân nào cũng bén hỏa; địch dù đứng dù chạy, thảy bị hỏa vân nung đến kiệt cùng.',
  tuyQuyen: 'Say mà chẳng loạn, thân nghiêng chiêu hiểm. Người tưởng ăn mày ngã nghiêng theo men, đâu hay mỗi cú vung tay ẩn sát cơ khôn dò.',
  khangLongTamChuong: 'Chưởng lực chính đại, tiếng ngân như rồng. Quang minh hào hùng, nhất chưởng đẩy ra chấn động sơn hà; cường địch trúng đòn cũng phải nao lòng lùi bước.',
  khangLongThapBatChuong: 'Dịch lý làm căn, mười tám chưởng rồng. Cương mà chẳng cứng, nhất chiêu giáng xuống như thần long xuất hải; uy chấn thiên hạ, hào khí ngất trời.',
  khaiTuuThuc: 'Mượn men khai mạch, chân khí bừng bừng. Nhất hớp rượu vào, khí lực trào dâng; càng đấu càng hăng, quyền cước cuồn cuộn chẳng hề suy.',
  dangLongCuoc: 'Mượn thế rồng bay, nhất cước xuyên mây. Thân hình thăng thiên, sức cước trầm hùng; giáng xuống đầu địch như sấm bổ non cao, khôn bề né tránh.',
  tiemThienChuong: 'Lấy nhu chứa cương, chưởng ẩn chưa phát. Rồng nấp vực sâu chờ thời điểm; một khi động thân, thế không gì cản, âm thầm mà hiểm ác khôn lường.',
  phiLongTaiThien: 'Rồng bay giữa trời, khí thế bao trùm. Nhất chưởng phi long vươn mình, chưởng phong quét ngang thiên hạ; quần hùng ngước nhìn, thảy phải kính phục.',
  nhatNguyetTamPhap: 'Dung hợp nhật nguyệt, âm dương một mạch. Nội tức thâm hậu khôn lường, càng luyện càng cường; đặt nền cho vạn ban tà công quỷ dị của Thần Giáo.',
  quangMinhTanPhap: 'Chân khí tỏa rạng, sáng tựa vầng dương. Nhất chiêu tán phát bốn phương, ánh quang chói lòa áp đảo quần địch; uy nghi lẫm liệt, khôn cùng.',
  huyetTeThuc: 'Lấy máu làm lễ, dẫn sát khí nhập thân. Uy lực kinh người mà âm hàn thấu cốt; mỗi lần thi triển, một lần dâng máu cầu cường.',
  phanHuyetChuong: 'Đốt cháy khí huyết, chưởng phong ám đỏ. Nhất chưởng phần huyết giáng xuống, máu trong thân địch sôi trào; đau đớn thấu tâm can chỉ trong khoảnh khắc.',
  nhiepHuyetThuc: 'Hút cạn tinh huyết, nạp về bồi thân. Địch càng suy mà mình càng vượng; song tà khí dồn tụ, sớm muộn cũng sinh hậu hoạn khôn lường.',
  huyetHaiThichCot: 'Hiểm độc thấu xương, chiêu ra như biển máu ngập trời. Sát khí lạnh buốt xuyên tận tâm can; kẻ trúng đòn đau đến tận cốt, khó lòng toàn mạng.',
  // --- THỔ ---
  lienHoanThoiTuy: 'Chưởng trấn Võ Đang, kình liên bất tuyệt. Nhất thức dẫn bách thức, sóng cuộn tầng tầng; đẩy tới ép lui, địch chẳng kịp hoàn thủ, chỉ đành thoái lui.',
  tuLuongBatThienCan: 'Diệu lý Thái Cực, mượn lực hoàn lực. Tứ lạng kéo ngàn cân, dĩ nhu chế cương; kẻ càng mạnh bạo, càng tự chuốc bại vong.',
  luongNghiThuc: 'Kiếm ý Võ Đang, phân âm dương lưỡng nghi. Tả hư hữu thực, một thân tựa hai người vây kích; địch hoa mắt loạn tâm, chẳng biết chân giả.',
  nhuVanChuong: 'Chưởng phong Võ Đang, mềm tựa mây trôi. Vô hình vô sắc, phiêu diêu ẩn kình; chạm rồi mới hay lực đã thấm tạng phủ, muốn tránh đã muộn.',
  thaiCucNhuKinh: 'Tinh túy Thái Cực, dĩ nhu khắc cương, dĩ tĩnh chế động. Kình vận vòng tròn miên miên bất đoạn, tá lực đả lực; sức địch tan vào hư không.',
  luongNghiSinhTu: 'Thượng thừa Võ Đang, lưỡng nghi sinh tứ tượng. Âm dương xoay chuyển, tỏa bốn phương tám hướng; nhất chưởng hàm muôn nghìn biến, đạo pháp tự nhiên khôn dò.',
  conLonChuong: 'Chưởng trấn Côn Lôn, hùng hồn khai hoát. Nhất chưởng khai ra, khí thế trập trùng như non xa; cương mãnh mà chẳng mất phần chính đại quang minh.',
  toaThienCuong: 'Trận trấn Côn Lôn, dẫn khí trời đất kết lưới cương. Bố theo tinh tú, khóa chặt bốn phương; địch sa thiên la địa võng, tiến thoái đều nan.',
  honNguyenNhatKhi: 'Nội công Côn Lôn, tinh khí thần quy nhất. Chân khí thuần hậu, miên mật như thái sơ vị phân; càng luyện càng thâm, nền cho muôn vàn tuyệt kỹ.',
  khaiThienXucDia: 'Tuyệt học Côn Lôn, khí thế khai thiên lập địa. Nhất chiêu giáng xuống, chấn động sơn hà; cương kình bạo liệt, phá tan mọi phòng ngự trước mặt.',
  canKhonNhatChi: 'Chỉ pháp Côn Lôn, toàn thân chân khí dồn nơi đầu ngón. Càn khôn thu một chỉ, cách không điểm huyệt; kình xuyên hư không, hàm lẽ trời đất trong khoảnh khắc.',
  daoChuyenAmDuong: 'Bí thuật Côn Lôn, đảo chuyển càn khôn, nghịch chuyển khí cơ. Biến hư thành thực, đổi công làm thủ; chiêu địch loạn ngũ hành, tự phản kinh mạch.',
  conLonTamThucKiem: 'Kiếm Côn Lôn ba thức, thức thức hàm thiên cơ. Ba chiêu liền nhau như non liền non, biển tiếp biển; giản dị mà uy mãnh, nhất kiếm định sinh tử.',
  thienSonHanBang: 'Chưởng trấn Thiên Sơn, hàn khí thấu xương tựa tuyết phủ đỉnh non. Chưởng vừa chạm, khí huyết đóng băng; lạnh buốt tê tâm, cử động cũng chẳng còn.',
  bangPhachHoThan: 'Hộ thân Thiên Sơn, vận hàn khí kết băng phách quanh thân. Cương nhu tương tế, ngoại lực chạm liền bị phản chấn; thủ vững như thành băng vạn dặm.',
  lucDuongThanCong: 'Thần công thuần dương Thiên Sơn, dung sáu đường dương khí ôn nhu mà hùng hậu. Dĩ dương hòa âm, điều hợp hàn nhiệt; chân khí sinh sôi, vừa liệu thương vừa tăng công lực.',
  thienSonChiHan: 'Chỉ pháp âm hàn Thiên Sơn, tụ hàn khí bắn ra như kim băng. Điểm huyệt phong bế kinh mạch, giá lạnh lan tràn; địch cứng đờ tê dại, chẳng thể vận công.',
  hoiXuanThuat: 'Y thuật Thiên Sơn, chân khí ôn hòa dẫn nhập kinh mạch, cải tử hoàn sinh. Một hơi hồi xuân xua tan thương thế; khí huyết lưu thông, người kiệt lại bừng sinh khí.',
  hanBangChanKhi: 'Nội công Thiên Sơn, chân khí âm hàn tinh thuần chảy khắp châu thân. Hàn khí thâm trầm như băng tuyết ngàn năm; nền tảng cho mọi băng chưởng hàn chỉ bản phái.',
  thienSonBangPhong: 'Tuyệt học Thiên Sơn, dồn hàn khí thành cuồng phong băng tuyết quét ngang trời. Sương giá phủ kín chiến trường, phong tỏa vạn vật; nhất chiêu chôn địch trong giá rét.',
  // --- Neutral (vô phái) ---
  coBanChuong: 'Nhất chưởng bình xuất, vô hoa vô xảo. Chiêu chẳng huyền diệu, thế lại đường hoàng; căn cơ vững vàng, vạn pháp do đây mà sinh.',
  hoThanBo: 'Dời gót né đòn, thu vai giữ thế. Loạn quân đao kiếm chẳng chạm được thân; bộ chưa thành danh, đủ toàn tính mạng giữa vòng vây.',
  vinhXuanChuy: 'Thủ trung tuyến, đấm thẳng liên hoàn. Lấy tĩnh chế động, tam quyền dồn nhất điểm; mạnh yếu phân minh, chỉ trong khoảnh khắc.',
  vanKhiQuyet: 'Điều tức dẫn khí, chu thiên tuần hoàn. Tạp niệm gột sạch, đan điền mỗi lúc mỗi hậu; nội tức trầm sâu, ấy nền của đại đạo.',
  toanPhongCuoc: 'Xoay người tung cước, nhất chuyển quét ngang. Cuồng phong khởi tại gót chân, thế đến hung mãnh; địch vây bốn phía, chớp mắt đã tan.',
  // --- THẦN THOẠI (bí kíp 9 huyền thoại) ---
  camHuongHoaiCotTan: 'Hương thơm cẩm tú, ngầm ẩn nọc hoại cốt. Kẻ trúng độc mỉm cười, gân xương rã dần trong mê; hương chưa tàn mà mệnh đã tuyệt, chết chẳng hay.',
  tamCotDuongSinhCo: 'Cổ tằm gặm xương, hút nội tức địch dưỡng thân. Đối thủ càng vùng vẫy, độc càng thấm sâu; địch tận nguyên khí, ta được trường sinh.',
  phanTamCuuDiem: 'Chín ngọn liệt diễm, thiêu tận tâm can. Chưởng phong đến đâu, hồng liên bùng cháy đến đó; thịt xương hóa tro, chẳng chừa một tấc sống.',
  phucMaBatDongThien: 'Tâm bất động như sơn, thân vững tựa kim cương. Muôn vàn tà lực đập tới, tan biến trước một niệm từ bi; ma khí chẳng thể xâm, đạo tâm bất khả phạm.',
  lacMaiNhatKiem: 'Một kiếm điểm ra, như mai rụng đầu cành. Thanh nhã mà chí mệnh; tuyết hoa vừa lả tả, kiếm đã xuyên yết hầu.',
  hanhVanLuuThuyQuyet: 'Người đi như mây trôi, thế đến tựa nước chảy. Không đầu không cuối, đòn nối bất tuyệt; mềm mại vô hình mà cuốn phăng địch theo dòng.',
  doanHuyenThapTamTuyen: 'Mười ba dây tơ, hóa mười ba sát cơ. Tiếng đàn vừa dứt, âm ba chấn động phế phủ; người nghe đứt ruột mà chẳng thấy máu rơi.',
  nhatNhanDoanMenhThich: 'Một liếc khóa mệnh, một thích đoạt hồn. Ra tay thần tốc, chẳng ai kịp thấy; chỉ nghe tiếng gió, tử huyệt đã trúng.',
  hanBangCuuTuyetChuong: 'Chín thức cực hàn, đóng băng khí huyết địch nhân. Chưởng phong đến đâu, sương giá tràn đến đó; gân mạch cứng đờ, một chiêu định sinh tử.',
};
