// ============================================================
// ĐĂNG TIÊN MỘNG — lore (flavor) 109 thẻ MỚI. Soạn qua workflow 6-agent (5 hệ + neutral/Thần Thoại)
// + harmonize (giọng võ lâm/tu tiên, tiếng Việt CÓ DẤU, không chép nguyên). 17 thẻ [C] cũ giữ flavor trong POOL.
// Số DRAFT về nội dung — user tinh chỉnh thẻ nào chưa ưng.
// ============================================================
export const CARD_LORE = {
  // --- KIM ---
  kimCangGiap: 'Ngạnh công trấn bang của Thiên Vương Bang, vận khí thành giáp bọc kín toàn thân. Đao thương chém tới chỉ nghe tiếng chát rồi trượt đi, thân như đúc bằng kim cương, ngoại lực khó tổn phân hào.',
  phanChanChuong: 'Chưởng pháp cương mãnh của Thiên Vương Bang, mượn lực đánh lực. Địch nhân vừa chạm vào liền bị chấn kình bật ngược, đòn càng nặng thì phản đòn càng dữ, tự chuốc lấy thương tổn.',
  tieuThietChuong: 'Tuyệt kỹ luyện thủ của Thiên Vương Bang, hai bàn tay tôi trong lửa sắt tro tàn. Chưởng phong tới đâu thép nóng chảy tan, thịt phàm cứng tựa kim loại, một chưởng đủ tiêu tan gang thép.',
  phaThietChuy: 'Trọng thủ pháp của Thiên Vương Bang, tụ cả sức nặng đất trời vào một chùy. Nhằm chỗ hiểm mà giáng xuống, thiết giáp dày mấy tấc cũng vỡ nát, uy thế trầm hùng long trời lở đất.',
  thietTuongBich: 'Thủ pháp trấn thủ của Thiên Vương Bang, đứng lặng như bức tường sắt sừng sững. Muôn đòn dập tới đều bị chặn đứng ngoài thân, vững vàng bất động, một người án ngữ vạn quân khó qua.',
  phaGiapTamChuy: 'Sát chiêu của Thiên Vương Bang, ba chùy liền nhau như sấm nối sấm. Chùy đầu phá giáp, chùy sau vỡ cốt, chùy cuối định mạng, kẻ mang giáp trụ dày cũng khó lòng đỡ trọn ba đòn.',
  kimCuongPhachToai: 'Cương mãnh tuyệt học của Thiếu Lâm, vận Kim Cang bất hoại vào song thủ. Một chưởng giáng ra như búa thần bổ xuống, đá tảng vỡ tan, tà ma nghe tiếng đã kinh hồn bạt vía.',
  thietBoSam: 'Ngoại công hộ thể trứ danh Thiếu Lâm, luyện da thịt bền như tấm áo sắt. Đao kiếm chém vào chỉ để lại vệt trắng, thân trần mà đỡ được binh nhận, thiền công thâm hậu ẩn trong.',
  viDaChuong: 'Chưởng pháp hộ pháp của Thiếu Lâm, lấy tên Vi Đà tôn giả trấn sơn môn. Chưởng phong đường hoàng chính đại, cương trung có nhu, một chưởng phát ra hàng yêu phục ma, hộ trì Phật pháp.',
  baNhaThung: 'Tuyệt kỹ chấn động của Thiếu Lâm, kình lực rung ngân như đại hồng chung Bá Nhã. Đòn đánh vô thanh mà chấn thẳng vào phủ tạng, ngoài da lành lặn nhưng nội phủ đã tan, âm ba khó lường.',
  vanVuThan: 'Thân pháp tiêu diêu của Bồng Lai, bước đi như mây trôi mưa cuốn giữa non tiên. Thoắt ẩn thoắt hiện phiêu hốt vô định, địch nhân hoa mắt chẳng lần được tung tích, nhẹ tựa vân yên.',
  ngocLoTuKhi: 'Tâm pháp dưỡng khí của Bồng Lai, hớp móc ngọc sương mai tụ linh khí vào đan điền. Chân nguyên ôn nhuận sinh sôi không dứt, tựa uống cam lộ tiên gia, nội tức miên miên bất tuyệt.',
  phiKiemTruyThan: 'Kiếm quyết ngự khí của Bồng Lai, điều khiển phi kiếm vượt trăm bước lấy đầu người. Kiếm quang lóe lên như sao băng truy hồn, nhanh đến mức thần cũng khó tránh, hình bóng chưa tan mạng đã mất.',
  thanhVanBo: 'Bộ pháp đăng vân của Bồng Lai, chân đạp thanh vân bước lên chín tầng trời. Thân hình khinh linh phiêu dật, tiến thoái tựa đạp mây lướt gió, phàm nhân trông theo ngỡ tiên nhân giáng thế.',
  tienNhanChiLo: 'Chỉ pháp huyền diệu của Bồng Lai, một ngón trỏ ra như tiên nhân điểm hóa mê đồ. Kiếm khí tụ nơi đầu ngón phóng thẳng huyệt đạo, tưởng nhàn nhã mà ẩn sát cơ, điểm trúng liền định thắng thua.',
  luuVanPhi: 'Kiếm pháp phiêu hốt của Bồng Lai, kiếm đi như mây lành lững lờ rồi chợt bùng thành bão. Chiêu thức nhu hòa quấn quýt liên miên bất tuyệt, trong nhẹ nhàng giấu sát ý, khiến địch khó dò hư thực.',
  tieuDaoDonKiem: 'Đốn kiếm tự tại của Bồng Lai, ngự kiếm độn quang chớp mắt đã ngoài trăm dặm. Người kiếm hợp nhất tiêu diêu thiên địa, đến đi không dấu vết, phiêu nhiên thoát tục như bậc tiên gia du ngoạn.',
  // --- MỘC ---
  manThienPhi: 'Ám khí tuyệt học Đường Môn, mười ngón một vẩy liền có trăm mũi phi hoàng che kín trời cao. Địch đông đến đâu cũng khó bề tránh né, ngẩng đầu chỉ thấy mưa thép rợp đất.',
  thoiTamChau: 'Tuyệt kỹ ngầm của Đường Môn, một viên châu nhỏ bắn thẳng vào tâm mạch đối thủ. Thủ pháp âm nhu mà hiểm hóc, trúng rồi mới hay kình lực đã xuyên tận đáy lòng.',
  phiTienThuat: 'Xạ nghệ chân truyền Đường Môn, tiễn rời cung như sao băng xé gió. Trăm bước xuyên dương, mắt vừa chớp thì mũi tên đã cắm ngập nơi yếu hại.',
  tuTinhCham: 'Độc châm bí truyền Đường Môn, thân kim tím biếc mảnh như tơ liễu. Vô thanh vô tức lẩn vào gió, sượt qua da thịt là kịch độc đã ngấm vào gân cốt.',
  khongMinhVu: 'Nỏ liên châu chế theo di pháp Khổng Minh, một cơ quan bật ra hàng loạt tiễn dày đặc. Đường Môn cải tiến thêm phần tinh xảo, tay không ngừng thì tiễn chẳng dứt.',
  vanTienTruQuang: 'Xạ thuật đỉnh cao Đường Môn, vạn tiễn đồng loạt vọt lên rồi lao xuống truy hình đuổi bóng. Đã khóa mục tiêu thì dù chạy nhanh tựa ánh sáng cũng không thoát khỏi lưới tiễn.',
  ngungDocTan: 'Độc công nhập môn của Ngũ Độc giáo, luyện trăm loài độc trùng thành một nắm bột tán. Gió thoảng qua là chất kịch độc ngưng tụ lan khắp, kẻ hít phải liền tê dại tứ chi.',
  vanDocQuiTong: 'Đại pháp trấn giáo của Ngũ Độc, gom vạn độc trong thiên hạ quy về một mối. Độc chồng lên độc, càng lâu càng thịnh, khiến đối thủ ngũ tạng dần rữa nát.',
  docLongToa: 'Cầm nã thủ pháp tẩm độc của Ngũ Độc giáo, xích độc long quấn siết như trăn quấn mồi. Đã khóa được thì độc theo khớp xương chảy vào, càng vùng vẫy độc càng thấm sâu.',
  tanDocThu: 'Chưởng pháp âm độc của Ngũ Độc, mười ngón nhuộm màu chàm phất ra làn độc vụ. Vỗ trúng thân người là hàn độc tán khắp kinh mạch, khí huyết đình trệ chẳng còn nghe lời.',
  nguDocXaTien: 'Ám khí độc môn của Ngũ Độc giáo, mũi tiễn khắc hình xà đầu tẩm nọc năm giống độc trùng. Tên bay rít lên như rắn phun nọc, trúng rồi thì độc theo máu bò thẳng về tim.',
  cotDocChuong: 'Chưởng công thâm hiểm của Ngũ Độc, kình lực xuyên qua da thịt mà thấm thẳng vào xương tủy. Trúng chưởng chẳng thấy vết ngoài, chỉ nghe cốt độc ăn dần đến khi gân cốt tê liệt.',
  bachDocPhat: 'Tuyệt kỹ áp giáo của Ngũ Độc, dồn trăm loại độc ẩn trong người rồi cùng lúc phát tác. Bách độc đồng thời bùng lên, kẻ trúng chỉ trong khoảnh khắc đã bị độc khí thiêu đốt lục phủ.',
  huyetMaCong: 'Ma công tà đạo trấn phái Ma Giáo, dẫn huyết khí sôi trào hóa thành cuồng lực bạo liệt. Càng đánh càng hăng như say máu, uy mãnh kinh người nhưng dễ tổn hại chân nguyên.',
  nhiepHonThuat: 'Nhiếp tâm tà thuật của Ma Giáo, ánh mắt cùng ma âm nhiễu loạn thần trí đối thủ. Hồn phách bị khống chế trong chớp mắt, kẻ địch ngơ ngác như mất cả tâm thần.',
  huyetTraoThu: 'Trảo pháp đẫm máu của Ma Giáo, năm ngón cong như móc câu xé toạc da thịt hút lấy huyết khí. Vuốt tới đâu máu bắn tới đó, càng cào càng thêm cuồng bạo.',
  thichHuyetChu: 'Ma chú hút máu của Ma Giáo, khắc lời nguyền huyết lên đối thủ để hằng đêm hút dần tinh huyết. Bị dính chú thì máu thịt hao mòn không dứt, uy lực âm hiểm khôn lường.',
  huyetTeChuong: 'Chưởng pháp tế luyện của Ma Giáo, lấy máu tươi làm lễ khơi dậy ma khí trong lòng bàn tay. Một chưởng giáng xuống mang theo sát khí ngút trời, đổi mạng địch bằng chính huyết khí của mình.',
  phanHuyetHoiNguyen: 'Ma pháp hồi nguyên của Ma Giáo, đốt cháy huyết khí trong người để bức bách chân nguyên phục hồi. Trong chớp mắt bùng lên sinh cơ mãnh liệt, song đốt máu tiếp lực rốt cuộc là tổn thọ chuốc họa về sau.',
  // --- THỦY ---
  phatQuangKinh: 'Trấn phái tâm kinh Nga Mi, dẫn Phật quang phổ chiếu quanh thân. Vận công thì hào quang bao bọc, tà khí khó xâm, gươm đao chạm vào cũng tan như sương sớm.',
  phoDoTe: 'Đại lễ từ bi của Nga Mi, tụng kinh cầu độ chúng sinh khổ nạn. Pháp lực lan tỏa như nước cam lồ, xoa dịu thương tổn, kéo đồng đạo khỏi bờ vực sinh tử.',
  thanhTamChu: 'Chú ngữ tịnh tâm truyền đời Nga Mi, một niệm tĩnh thì muôn niệm lặng. Trừ được tà mị nhiễu loạn tâm thần, giữ linh đài trong vắt như mặt hồ không gợn.',
  phoHienChuong: 'Hộ pháp chưởng lấy hồng danh Phổ Hiền Bồ Tát, cương nhu tương tế mà từ bi. Chưởng ra trầm ổn như núi, vừa hộ thân che chở, vừa điểm hóa kẻ mê muội quay đầu.',
  chuDuongTamChu: 'Bí chú dưỡng tâm hộ mệnh của Nga Mi, ngày đêm tụng niệm nuôi dưỡng nguyên thần. Hộ tâm mạch vững bền, tà độc khó lấn, khí huyết tự an như suối chảy không ngừng.',
  tuBiPhoDo: 'Chưởng pháp Nga Mi lấy lòng từ bi làm gốc, độ hết chúng sinh trong bể khổ. Một chưởng mở ra vừa hàng ma vệ đạo, vừa gieo phúc lành như mưa pháp thấm nhuần vạn vật.',
  matKiem: 'Kiếm pháp trấn sơn Hoa Sơn, chiêu thức ẩn hiện như mai hoa nở giữa tuyết. Sát cơ giấu trong nét đẹp thanh nhã, đối thủ chưa kịp nhìn ra đã trúng đòn hiểm.',
  phaKiemThuc: 'Tuyệt học phá địch của Hoa Sơn, chuyên nhắm sơ hở trong kiếm chiêu kẻ thù. Một kiếm điểm đúng phá thế, khiến trăm chiêu hoa mỹ của địch thủ tan vỡ trong nháy mắt.',
  cuongPhongKiem: 'Kiếm pháp Hoa Sơn lấy ý cuồng phong vô định, thế kiếm biến ảo không lường. Ra chiêu như gió lốc cuốn qua, hư thực khó phân, khiến đối phương chống đỡ không kịp trở tay.',
  lacThacKiem: 'Kiếm chiêu Hoa Sơn phóng túng buông thả, thế đi lãng đãng tựa kẻ say. Nhìn tưởng hờ hững vô lực, ngờ đâu trong sơ hở lại giấu sát cơ đoạt mệnh.',
  ngocNuKiem: 'Kiếm pháp Hoa Sơn thanh tú như dáng ngọc nữ, thế kiếm mềm mại mà tinh diệu. Chiêu thức uyển chuyển liền mạch, đôi kiếm hô ứng như bóng với hình, đẹp mà lợi hại khôn cùng.',
  tuTuKiem: 'Tuyệt kỹ Hoa Sơn tựa liễu nhứ đầy trời, kiếm quang mịt mù giăng kín tứ phương. Điểm điểm hàn mang như bông liễu bay, khiến đối thủ lạc giữa trùng trùng kiếm ảnh.',
  hanBangChuong: 'Chưởng pháp trấn phái Thúy Yên, hàn khí miên miên thấm vào tận cốt. Chưởng phong lạnh buốt như băng tuyết cuốn qua, đối thủ trúng đòn thì gân cốt tê cứng, khí huyết ngưng trệ.',
  bangPhongToa: 'Huyền công Thúy Yên vận huyền băng phong tỏa tứ phương, giá lạnh giăng thành lao ngục vô hình. Một khi thi triển thì bước chân địch thủ bị đông cứng, tiến thoái đều nan.',
  vanLyBangPhong: 'Kiếm pháp Thúy Yên mang khí thế vạn dặm băng phong, kiếm quang lạnh lẽo cuốn theo hàn sương. Một kiếm quét ra như bão tuyết ngàn trùng, đóng băng cả sát khí đối phương.',
  bangChamThich: 'Kiếm chiêu Thúy Yên tụ hàn khí thành băng châm nhỏ nhọn, ra tay mau lẹ vô thanh. Mũi kiếm lạnh như kim băng đâm tới, điểm trúng huyệt đạo khiến địch tê buốt khó lường.',
  lanhSuongThu: 'Thủ pháp hộ thân của Thúy Yên, vận lãnh sương kết thành màn hàn khí quanh mình. Sương lạnh giăng che chắn thân pháp, vừa thủ vững vừa khiến kẻ đến gần phải run tay chùn bước.',
  bangPhongChuong: 'Chưởng pháp Thúy Yên dồn băng phong vào một kích, hàn khí bộc phát như bão tuyết. Chưởng ra lạnh thấu tâm can, phong tỏa kinh mạch đối thủ, tê liệt cả chân tay.',
  tuyetPhongChuong: 'Tuyệt học Thúy Yên cuốn tuyết phong thành cuồng lưu giá lạnh, uy thế mãnh liệt khôn lường. Chưởng phong quét qua như trận tuyết bạo, vùi lấp đối thủ trong hàn khí ngập trời.',
  // --- HỎA ---
  phanThienChuong: 'Tuyệt học Thiên Nhẫn lấy tâm hỏa hun đúc, một chưởng giáng xuống như thiêu đốt cả trời. Khí nóng bừng bừng, đá tan vàng chảy, đối thủ chưa kịp lùi đã hóa tro tàn giữa cuồng viêm.',
  hoaVanCuongPhong: 'Chưởng phong cuốn theo mây lửa, gió độc Thiên Nhẫn quét ngang chiến địa. Một trận cuồng phong hực nóng ập tới, thiêu rụi vạn vật, khiến kẻ địch tán loạn trong biển hỏa vô hồi.',
  liaoNguyenChiHoa: 'Diệu pháp Thiên Nhẫn dẫn nguyên hỏa từ đan điền phun trào, đốm lửa nhỏ mà đủ liệu trọn cánh đồng. Ngọn nguyên hỏa bùng lên bất tận, càng cháy càng mạnh, thiêu tận cội rễ đối phương.',
  tinhHoaMoi: 'Chỉ một tia tinh hỏa nhỏ nhoi làm mồi, Thiên Nhẫn khơi dậy ngọn lửa liên miên bất tuyệt. Đốm lửa âm ỉ bén dần, chớp mắt bùng thành thế cháy lan không sao dập nổi.',
  lieuHoaChuong: 'Chưởng pháp liệu hỏa của Thiên Nhẫn, mỗi cái vỗ tay là một mồi lửa gieo vào thân địch. Lửa bén âm thầm, đối thủ càng động càng cháy, thịt xương dần tan trong ngọn viêm độc dai dẳng.',
  phanThienDoiHoa: 'Tuyệt kỹ Thiên Nhẫn dồn hỏa khí đối trọi giữa trời đất, lấy lửa chọi lửa mà áp đảo. Một chưởng phần thiên bùng cháy ngất trời, đè bẹp mọi phản kích, thiêu sạch cả chiến trường.',
  phucDiaHoaVan: 'Thiên Nhẫn rải mây lửa phủ khắp mặt đất, biến chiến địa thành một tấm thảm viêm hỏa. Bước chân nào cũng bén lửa, kẻ địch dù đứng dù chạy đều bị hỏa vân âm ỉ nung đến kiệt cùng.',
  tuyQuyen: 'Quyền pháp Cái Bang say mà chẳng loạn, thân lảo đảo mà chiêu hiểm khôn lường. Người ngoài tưởng gã ăn mày say rượu ngã nghiêng, đâu ngờ mỗi cú vung tay lại ẩn sát cơ khó dò.',
  khangLongTamChuong: 'Ba chưởng dẫn nhập Kháng Long của Cái Bang, cương mãnh hào hùng, tiếng chưởng như rồng ngân. Chưởng lực chính đại quang minh, một chưởng đẩy ra chấn động sơn hà, đủ làm nao núng cường địch.',
  khangLongThapBatChuong: 'Trấn bang tuyệt học Cái Bang, mười tám chưởng rồng lấy Dịch lý làm căn cốt. Chưởng cương mà chẳng cứng, một chiêu giáng xuống như thần long xuất hải, uy chấn thiên hạ, hào khí ngất trời.',
  khaiTuuThuc: 'Chiêu khai tửu của Cái Bang, mượn men rượu khơi thông kinh mạch, khí lực bừng bừng. Một hớp rượu vào là chân khí trào dâng, càng đấu càng hăng, quyền cước cuồn cuộn chẳng hề suy.',
  dangLongCuoc: 'Cước pháp Cái Bang mượn thế rồng bay vút lên, một cước đá thẳng chín tầng mây. Thân hình đăng long thăng thiên, sức cước trầm hùng, giáng xuống đầu địch như sấm bổ non cao.',
  tiemThienChuong: 'Chưởng pháp tiềm tàng của Cái Bang, lấy nhu chứa cương, chưởng chưa phát mà uy đã ẩn. Rồng nấp nơi vực sâu chờ thời, một khi phát động thì thế không gì cản, âm thầm mà hiểm ác vô cùng.',
  phiLongTaiThien: 'Chưởng thế Cái Bang như rồng bay giữa trời cao, khí thế bao trùm cả bốn phương. Một chưởng phi long vươn mình, chưởng phong quét ngang thiên hạ, khiến quần hùng phải ngước nhìn kính phục.',
  nhatNguyetTamPhap: 'Tâm pháp trấn giáo Nhật Nguyệt, dung hợp âm dương nhật nguyệt vào một mạch chân khí. Nội tức thâm hậu khôn lường, càng luyện càng cường, đặt nền cho vô số tà công quỷ dị của Thần Giáo.',
  quangMinhTanPhap: 'Tán pháp quang minh của Nhật Nguyệt, chân khí tỏa ra rực rỡ như vầng nhật soi. Một chiêu tán phát bốn phương, ánh sáng chói lòa áp đảo quần địch, uy nghi mà lẫm liệt khôn cùng.',
  huyetTeThuc: 'Tà thuật tế huyết của Nhật Nguyệt Thần Giáo, lấy máu làm lễ, dẫn sát khí quỷ dị nhập thân. Uy lực kinh người mà âm hàn thấu cốt, mỗi lần thi triển là một lần dâng máu cầu cường.',
  phanHuyetChuong: 'Chưởng pháp Nhật Nguyệt đốt cháy khí huyết địch nhân, chưởng phong ám đỏ tanh nồng. Một chưởng phần huyết giáng xuống, máu trong thân địch như sôi trào, đau đớn thấu tâm can trong khoảnh khắc.',
  nhiepHuyetThuc: 'Chiêu nhiếp huyết tà môn của Nhật Nguyệt, hút cạn tinh huyết đối thủ nạp về bồi bổ chính mình. Càng đấu địch càng suy mà mình càng vượng, song tà khí dồn tụ, sớm muộn cũng sinh hậu hoạn.',
  huyetHaiThichCot: 'Tuyệt kỹ Nhật Nguyệt Thần Giáo hiểm độc thấu xương, chiêu ra như biển máu ngập trời đâm vào cốt tủy. Sát khí lạnh buốt xuyên tận tâm can, kẻ trúng đòn đau đến tận xương, khó lòng toàn mạng.',
  // --- THỔ ---
  lienHoanThoiTuy: 'Chưởng pháp trấn phái Võ Đang, kình lực liên miên bất tuyệt như sóng cuộn. Một thức phát ra dẫn theo trăm thức, đẩy tới ép lui khiến địch nhân không kịp hoàn thủ, chỉ đành thoái lui.',
  tuLuongBatThienCan: 'Diệu lý Thái Cực của Võ Đang, mượn sức đối phương mà hoàn trả về chính họ. Bốn lạng kéo ngàn cân, lấy nhu chế cương, kẻ càng mạnh bạo lại càng tự chuốc bại vong.',
  luongNghiThuc: 'Kiếm ý Võ Đang phân âm dương hai nghi, tả hư hữu thực biến ảo khôn lường. Một mình mà tựa như hai người vây kích, khiến đối thủ hoa mắt loạn tâm, chẳng biết đâu là chân đâu là giả.',
  nhuVanChuong: 'Chưởng phong Võ Đang mềm mại tựa mây trôi, phiêu diêu vô ngại mà ẩn tàng nội kình. Vô hình vô sắc, chạm vào rồi mới hay kình lực đã thấm vào tạng phủ, muốn tránh đã muộn.',
  thaiCucNhuKinh: 'Tinh túy Thái Cực của Trương chân nhân Võ Đang, dĩ nhu khắc cương lấy tĩnh chế động. Kình lực vận theo vòng tròn miên miên bất đoạn, tá lực đả lực, khiến sức mạnh địch nhân tan biến vào hư không.',
  luongNghiSinhTu: 'Thượng thừa võ học Võ Đang, lưỡng nghi sinh tứ tượng biến hóa vô cùng. Âm dương xoay chuyển sinh ra bốn phương tám hướng, một chưởng hàm chứa muôn nghìn biến thức, đạo pháp tự nhiên khôn dò.',
  conLonChuong: 'Chưởng pháp trấn sơn Côn Lôn, hùng hồn khai hoát như núi cao vòi vọi. Một chưởng đánh ra khí thế trùng điệp tựa trập trùng non xa, cương mãnh mà không mất phần chính đại quang minh.',
  toaThienCuong: 'Trận pháp trấn phái Côn Lôn, dẫn khí trời đất kết thành lưới cương khí bủa vây. Bố trí theo tinh tú vận hành, khóa chặt bốn phương khiến kẻ địch sa vào thiên la địa võng, tiến thoái đều nan.',
  honNguyenNhatKhi: 'Nội công căn bản của Côn Lôn, luyện tinh khí thần quy về một mối hỗn nguyên. Chân khí thuần hậu miên mật như thái sơ vị phân, càng luyện càng thâm hậu, đặt nền cho muôn vàn tuyệt kỹ.',
  khaiThienXucDia: 'Tuyệt học cương mãnh của Côn Lôn, khí thế như khai thiên lập địa thuở hồng hoang. Một chiêu giáng xuống chấn động sơn hà, cương kình bạo liệt phá tan mọi phòng ngự trước mặt.',
  canKhonNhatChi: 'Chỉ pháp tuyệt luân của Côn Lôn, tụ toàn thân chân khí dồn nơi đầu ngón tay. Càn khôn thu vào một chỉ, kình lực xuyên phá cách không điểm huyệt, hàm chứa cả lẽ trời đất trong khoảnh khắc.',
  daoChuyenAmDuong: 'Bí thuật đảo chuyển âm dương của Côn Lôn, xoay chuyển càn khôn nghịch chuyển khí cơ. Biến hư thành thực đổi công làm thủ, khiến chiêu thức địch nhân bị đảo lộn ngũ hành, tự loạn kinh mạch.',
  conLonTamThucKiem: 'Kiếm pháp tinh diệu ba thức của Côn Lôn, mỗi thức đều hàm chứa thiên cơ vô tận. Ba chiêu liền nhau như núi liền non biển tiếp biển, giản dị mà uy mãnh, một kiếm định sinh tử.',
  thienSonHanBang: 'Chưởng pháp trấn phái Thiên Sơn, hàn khí băng lãnh thấu xương tựa tuyết phủ đỉnh non. Chưởng phong vừa chạm liền đóng băng khí huyết địch nhân, lạnh buốt tê tâm khiến cử động cũng chẳng còn.',
  bangPhachHoThan: 'Hộ thân tuyệt kỹ của Thiên Sơn, vận hàn khí kết thành lớp băng phách bao quanh thân mình. Cương nhu tương tế, ngoại lực chạm vào liền bị hàn khí phản chấn, thủ vững như thành băng vạn dặm.',
  lucDuongThanCong: 'Thần công thuần dương của Thiên Sơn, dung hòa sáu đường dương khí ôn nhu mà hùng hậu. Lấy dương hòa âm điều hợp hàn nhiệt, chân khí sinh sôi bất tuyệt, vừa liệu thương vừa tăng công lực.',
  thienSonChiHan: 'Chỉ pháp âm hàn của Thiên Sơn, tụ hàn khí nơi ngón tay bắn ra như kim băng. Điểm trúng huyệt đạo liền phong bế kinh mạch, giá lạnh lan tràn khiến đối thủ cứng đờ tê dại, không thể vận công.',
  hoiXuanThuat: 'Y thuật thượng thừa của Thiên Sơn, vận chân khí ôn hòa dẫn nhập kinh mạch cải tử hoàn sinh. Một hơi hồi xuân xua tan thương thế, khiến khí huyết lưu thông, người sắp kiệt lực lại bừng bừng sinh khí.',
  hanBangChanKhi: 'Nội công căn cơ của Thiên Sơn, luyện chân khí âm hàn tinh thuần chảy khắp châu thân. Hàn khí thâm trầm như băng tuyết ngàn năm, làm nền tảng cho mọi băng chưởng hàn chỉ của bản phái.',
  thienSonBangPhong: 'Tuyệt học bạo liệt của Thiên Sơn, dồn hàn khí thành cuồng phong băng tuyết quét ngang trời. Gió lạnh cuốn theo băng sương phủ kín chiến trường, phong tỏa vạn vật, một chiêu khiến kẻ địch chôn thân trong giá rét.',
  // --- Neutral (vô phái) ---
  coBanChuong: 'Chưởng pháp nhập môn của kẻ mới bước vào giang hồ, một chưởng ngang bằng bổ ra ngay ngắn. Tuy chẳng có gì huyền diệu, song là gốc rễ của muôn ngàn tuyệt học về sau.',
  hoThanBo: 'Bộ pháp hộ thân sơ khởi, dời gót tránh đòn, thu vai giữ thế. Chưa thành khí hậu nhưng đủ để kẻ luyện võ giữ được thân giữa loạn quân đao kiếm.',
  vinhXuanChuy: 'Chùy pháp ngắn gọn mà rắn rỏi, thủ trung tuyến, đấm thẳng liên hoàn. Lấy tĩnh chế động, ba đòn dồn về một chỗ, kẻ mạnh yếu chỉ trong khoảnh khắc phân minh.',
  vanKhiQuyet: 'Khẩu quyết điều tức dẫn khí lưu chuyển chu thiên, gột rửa tạp niệm trong đan điền. Nội tức mỗi ngày một hậu, ấy là nền móng cho kẻ mưu cầu đại đạo.',
  toanPhongCuoc: 'Cước pháp xoay người tung chân như lốc cuốn, một vòng quét ngang địch nhân bốn phía. Thế đến hung mãnh, cuồng phong khởi tại gót chân, chớp mắt đã dồn kẻ vây thành thế bại.',
  // --- THẦN THOẠI (bí kíp 9 huyền thoại) ---
  camHuongHoaiCotTan: 'Độc tán tuyệt truyền của Tiếu Diện Độc La Sát Lạc Vô Trần, hương thơm cẩm tú mà ẩn nọc hoại cốt. Kẻ trúng phải mỉm cười mà gân xương rã dần, chết trong mê hương chẳng hay.',
  tamCotDuongSinhCo: 'Cổ thuật âm độc của Vạn Độc Đỗ Dược, nuôi tằm gặm xương lấy nội tức địch làm dưỡng chất cho mình. Địch càng vùng vẫy độc càng thấm, chủ nhân nhờ đó dưỡng sinh trường thọ.',
  phanTamCuuDiem: 'Hỏa công bá đạo của Bán Diện Hồng Liên Nam Cung Liệt Hỏa, chín ngọn liệt diễm thiêu tận tâm can. Chưởng phong đi tới đâu, lửa hồng liên bùng cháy tới đó, thịt xương hóa tro chẳng chừa.',
  phucMaBatDongThien: 'Thiền công trấn ma của Không Tịch Thiền Sư Tịch Huyền, tâm bất động như núi, thân vững tựa kim cương. Muôn vàn tà lực đập tới đều tan biến trước một niệm từ bi bất khả xâm phạm.',
  lacMaiNhatKiem: 'Kiếm ý trác tuyệt của Mai Kiếm Lão Nhân Tề Mặc Sơn, một kiếm điểm ra như mai rụng đầu cành. Thanh nhã mà chí mệnh, tuyết hoa vừa lả tả thì kiếm đã xuyên yết hầu.',
  hanhVanLuuThuyQuyet: 'Thân pháp phiêu dật của Vân Vong Nương, người đi như mây trôi nước chảy, không đầu không cuối. Đòn thế nối nhau bất tuyệt, mềm mại vô hình mà cuốn phăng địch nhân theo dòng.',
  doanHuyenThapTamTuyen: 'Cầm âm sát pháp của Đoạn Huyền Cầm Tiên Lăng Tố Cầm, mười ba dây đàn hóa mười ba sát cơ. Tiếng tơ vừa dứt, âm ba chấn động phế phủ, người nghe đứt ruột mà chẳng thấy máu rơi.',
  nhatNhanDoanMenhThich: 'Ám khí tuyệt kỹ của Đoạn Hồn Nhất Nhãn Tô Uyển Nghiệt, một cái liếc khóa mệnh, một mũi phi thích đoạt hồn. Ra tay thần tốc chẳng ai kịp thấy, chỉ nghe tiếng gió là đã trúng tử huyệt.',
  hanBangCuuTuyetChuong: 'Băng chưởng cực hàn của Băng Phách Nữ Hiệp Hàn Y Sương, chín thức tuyệt lạnh đóng băng khí huyết địch nhân. Chưởng phong tới đâu sương giá tràn tới đó, gân mạch cứng đờ, một chiêu định sinh tử.',
};
